# Site settings ...
uri: igormilla.com
url: https://igormilla.com
name: Igor Milla
title: "@igormilla"
email: im@igormilla.com
author: Igor Milla
baseurl: ""
keywords: ""
description: "My personal site"
social_username: igormilla

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"

# Plugins ...
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
